### PR TITLE
feat: Support Testnet ENS, refactor: Improve wallet store

### LINKED ISSUE #59: Block "Apply" button on workstreams detail page if the user isn't logged in
image

### LINKED ISSUE #72: Adding testnet support
Right now it's unclear if you're on mainnet or testnet. Your wallet is managing this in some way, but not really. Currently I'm connected with a wallet that has an ENS name on rinkeby and my wallet is set up in rinkeby but somehow I see mainnet ens names.

### PR DESCRIPTION
**Pull request by efstajas**
Update`walletStore.chainId` when the network changes. Fetch ENS names from the current network and auto-reloads ENS names when the network is updated. Display a warning if the network !== mainnet. No longer crash the application and instead block the login button if no web3 wallet is present.

Resolves #72
Resolves #59

### CODE REVIEW

**Comment by efstajas** [comment]
Doesn't yet work properly when your wallet isn't connected. Will fix!

**Comment by efstajas** [comment]
Ended up rewriting the wallet store to be a bit nicer to use — no more need to constantly check `$walletStore.connected` before accessing `accounts`. It's now also capable of understanding that the network checked even when the wallet hasn't yet been connected.

I also added a state for when no web3 object is available on window:

Screenshot 2022-05-03 at 18 10 07

**Review by juliendonck — COMMENTED** [review]
This is great work. 

I was just thinking it would be nice to have a `network: rinkeby` or something somewhere in the header or footer.

**Comment by efstajas** [comment]
@juliendonck if network !== mainnet

Screenshot 2022-05-05 at 10 10 51

**Comment by efstajas** [comment]
Resolves #59

**Pull request merged**
