### PR TITLE
Feature: Adds themepicker to header

### PR DESCRIPTION
**Pull request by juliendonck**
Screenshot 2022-04-25 at 14 29 15

Signed-off-by: Julien Donck <hello@juliendonck.com>

### CODE REVIEW

**Comment by juliendonck** [comment]
Fastest was to just have a button for now. Will add functionality to just have the default come from your system

**Comment by efstajas** [comment]
cool! did you run into any problems with getting the system theme? in JS it should be rather straightforward to read it.

```js
if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    // dark mode
}```

⬆️ that's how you can get the system theme initially

```js
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
    const newColorScheme = event.matches ? "dark" : "light";
});
```
⬆️ and that's how you can create an event listener to update it automatically when the user changes their system theme

**Comment by juliendonck** [comment]
> cool! did you run into any problems with getting the system theme? in JS it should be rather straightforward to read it.
> 
> ```js
> if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
>     // dark mode
> }
> ```
> 
> ⬆️ that's how you can get the system theme initially
> 
> ```js
> window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
>     const newColorScheme = event.matches ? "dark" : "light";
> });
> ```
> 
> ⬆️ and that's how you can create an event listener to update it automatically when the user changes their system theme

Yeah I saw this. I couldn't immediately get it to work but I also kind of don't like this as a concept. I'd rather set my UI in either dark or light and then leave it. But I can imagine people liking the system set thing. I also don't know where we would put this setting and creating a whole settings page for it seems overkill.

**Comment by efstajas** [comment]
@juliendonck Pushed the commit as discussed — wanna take a look?

**Pull request merged**
