### PR TITLE
Explore page fixes

### PR DESCRIPTION
**Pull request by juliendonck**
Based on #54 

- [x] explore page
    - [x] remove buttons from card
    - [x] make consistent timeframe + rate component
    - [x] remove active workstreams
    - [x] can we show a status of the workstream
    - [x] could add the banner with x open applications
    - [x] can we show total grant rate and day rate

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
Can you add that little note about the `.env` file to the Readme file in this PR?

**Review by juliendonck — COMMENTED** [review]
- [ ] make timerate a sentence `1000 DAI over 12 weeks`
- [ ] remove action rows on explore, the `apply`-button on some makes it look like you can't apply to all
- [ ] make the explore cards fixed height but less
- [ ] add total in the proposed box on the application modal

**Comment by brandonhaslegs** [comment]
Should all mentions of "Workstreams" or "Workstream" be capitalized?

**Comment by juliendonck** [comment]
> Should all mentions of "Workstreams" or "Workstream" be capitalized?

You tell me. So that would be like, Create a Workstream?

**Comment by brandonhaslegs** [comment]
> You tell me. So that would be like, Create a Workstream?

Yeah do it!

**Comment by efstajas** [comment]
Screenshot 2022-05-03 at 10 18 02

Let's also add a little padding around the list at the bottom?

**Comment by brandonhaslegs** [comment]
> Let's also add a little padding around the grid at the bottom?

#66 66

**Review by efstajas — APPROVED** [review]

**Pull request merged**
